---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/10/23 16:21
---

---@class BlockLevel

local characterPz = require("lib/CharacterPZ")
local errHandler = require("lib/ErrHandler")
local perkFactoryPZ = require("lib/PerkFactoryPZ")

local BlockLevel = {}

--- **Block Level**
---@param character IsoGameCharacter
---@param currentPerkLevel int
---@param perk PerkFactory.Perk
---@param maxLevel int
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory : zombie.characters.skills.PerkFactory
function BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel, level)
    --print("dentro blockLevel")
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **Check if perk is null**
    if not perk then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    --- **Check if currentPerkLevel is null**
    if not currentPerkLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " currentPerkLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if maxLevel is null**
    if not maxLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " maxLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if level is not nil**
    if not level then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " level " .. errHandler.err.IS_NULL_LEVEL)
        return nil
    end

    -- ---@type float
    -- local convertLevelToXp_ = 0.0

    -- if currentPerkLevel >= maxLevel then
    --     ---@type int
    --     for level_ = 1, maxLevel do
    --         convertLevelToXp_ = convertLevelToXp_ +
    --                 perkFactoryPZ.convertLevelToXp(perk, level_)
    --     end
    -- end

    -- ---@type float
    -- local totalXp = ( convertLevelToXp_ -
    --         characterPz.getXp(character, perk))

    -- if totalXp == 0 then
    --     return
    -- end

    local totalXp = -level
    --print("totalXp: ", totalXp)
    characterPz.addXP_PZ(character, perk, totalXp, false, false, false)
end

---Calculate Block Level
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param level int
---@param CharacterMaxSkillTable table
---@param currentPerkLevel int|nil
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function BlockLevel.calculateBlockLevel(character, perk, level, CharacterMaxSkillTable, currentPerkLevel)
   
    --print("dentro calculateBlockLevel")
    --- **Check if character is nil**
    if not character then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **Check if CharacterMaxSkillTable is nil**
    if not CharacterMaxSkillTable then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                " CharacterMaxSkillTable " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if perk is nil**
    if not perk then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    --- **Check if level is nil**
    if not level then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                " level " .. errHandler.err.IS_NULL_LEVEL)
        return nil
    end

    -- Usa currentPerkLevel passato come parametro, altrimenti calcolalo (backward compatibility)
    if not currentPerkLevel then
        currentPerkLevel = characterPz.getPerkLevel_PZ(character, perk)
    end
    --print("livello attuale del perk: ", currentPerkLevel)
    local maxLevel = characterPz.EnumNumbers.TEN

    -- Accesso diretto O(1) invece di loop O(n)
    local perkId = perk:getId()
    local details = CharacterMaxSkillTable[perkId]

    if not details then
        -- Perk non tracciato nella tabella
        return
    end

    --print("dentro if v:getPerk() == perk")
    --print("v:getCurrentLevel(): ", details.currentLevel)
    --print("v:getMaxLevel(): ", details.maxLevel)

    if currentPerkLevel == maxLevel then
        return
    end

    if currentPerkLevel >= details.maxLevel then
        --print("dentro if currentPerkLevel >= v:getMaxLevel()")
        BlockLevel.blockLevel(character, perk, currentPerkLevel, details.maxLevel, level)
    end
end

-- --- **Check Level Max**
-- ---@param character IsoGameCharacter
-- ---@param perk PerkFactory.Perk
-- ---@param CreateCharacterMaxSkillObj CharacterBaseObj
-- ---@return void
-- --- - IsoGameCharacter : zombie.characters.IsoGameCharacter
-- --- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
-- function BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)
--     --- **Check if character is nil**
--     if not character then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 errHandler.err.IS_NULL_CHARACTERS)
--         return nil
--     end

--     --- **Check if perk is nil**
--     if not perk then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 errHandler.err.IS_NULL_PERK)
--         return nil
--     end

--     --- **Check if CreateCharacterMaxSkillObj is nil**
--     if not CreateCharacterMaxSkillObj then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 " CreateCharacterMaxSkillObj " .. errHandler.err.IS_NULL)
--         return nil
--     end

--     BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)
-- end

return BlockLevel