---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 14/10/23 16:21
---

---@class BlockLevel

local characterPz = require("lib/CharacterPZ")
local errHandler = require("lib/ErrHandler")
local perkFactoryPZ = require("lib/PerkFactoryPZ")

local BlockLevel = {}

--- **Block Level**
---@param character IsoGameCharacter
---@param currentPerkLevel int
---@param perk PerkFactory.Perk
---@param maxLevel int
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory : zombie.characters.skills.PerkFactory
function BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel, level)
    --print("dentro blockLevel")
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **Check if perk is null**
    if not perk then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    --- **Check if currentPerkLevel is null**
    if not currentPerkLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " currentPerkLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if maxLevel is null**
    if not maxLevel then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " maxLevel " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if level is not nil**
    if not level then
        errHandler.errMsg("BlockLevel.blockLevel(character, perk, currentPerkLevel, maxLevel)",
                " level " .. errHandler.err.IS_NULL_LEVEL)
        return nil
    end

    -- ---@type float
    -- local convertLevelToXp_ = 0.0

    -- if currentPerkLevel >= maxLevel then
    --     ---@type int
    --     for level_ = 1, maxLevel do
    --         convertLevelToXp_ = convertLevelToXp_ +
    --                 perkFactoryPZ.convertLevelToXp(perk, level_)
    --     end
    -- end

    -- ---@type float
    -- local totalXp = ( convertLevelToXp_ -
    --         characterPz.getXp(character, perk))

    -- if totalXp == 0 then
    --     return
    -- end

    local totalXp = -level
    --print("totalXp: ", totalXp)
    characterPz.addXP_PZ(character, perk, totalXp, false, false, false)
end

---Calculate Block Level
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param CharacterMaxSkillTable table
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function BlockLevel.calculateBlockLevel(character, perk, level, CharacterMaxSkillTable)
   
    --print("dentro calculateBlockLevel")
    --- **Check if character is nil**
    if not character then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **Check if CharacterMaxSkillTable is nil**
    if not CharacterMaxSkillTable then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                " CharacterMaxSkillTable " .. errHandler.err.IS_NULL)
        return nil
    end

    --- **Check if perk is nil**
    if not perk then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    --- **Check if level is nil**
    if not level then
        errHandler.errMsg("BlockLevel.calculateBlockLevel(character, CharacterMaxSkillTable, perk)",
                " level " .. errHandler.err.IS_NULL_LEVEL)
        return nil
    end

    local currentPerkLevel = characterPz.getPerkLevel_PZ(character, perk)
    --print("livello attuale del perk: ", currentPerkLevel) -- si blocca qui a volte. e non entra nel ciclo for. però se siamo arrivati qui vuol dire che CreateCharacterMaxSkillObj esiste se no ci saremmo bloccati prima col codice. quindi CreateCharacterMaxSkillObj è un oggetto valido ma i perk al suo interno non sono definiti magari? quindi errore nel decodePerkDetails? il ciclo for non da neanche errore, quindi non intera nulla.
    local maxLevel = characterPz.EnumNumbers.TEN

    for perkName, details in pairs(CharacterMaxSkillTable) do -- meglio iterare direttamente sulla tabella moddata, senza ricreare ogni volta sto inutile createcharactermaxskillobj.
        if perkName == perk:getId() then
            --print("dentro if v:getPerk() == perk")
            --print("v:getCurrentLevel(): ", details.currentLevel)
            --print("v:getMaxLevel(): ", details.maxLevel)
            if currentPerkLevel == maxLevel then
                return
            end
        
            if currentPerkLevel >= details.maxLevel then
                --print("dentro if currentPerkLevel >= v:getMaxLevel()")
                BlockLevel.blockLevel(character, perk, currentPerkLevel, details.maxLevel, level)
            end
            break
        end
    end
end

-- --- **Check Level Max**
-- ---@param character IsoGameCharacter
-- ---@param perk PerkFactory.Perk
-- ---@param CreateCharacterMaxSkillObj CharacterBaseObj
-- ---@return void
-- --- - IsoGameCharacter : zombie.characters.IsoGameCharacter
-- --- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
-- function BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)
--     --- **Check if character is nil**
--     if not character then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 errHandler.err.IS_NULL_CHARACTERS)
--         return nil
--     end

--     --- **Check if perk is nil**
--     if not perk then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 errHandler.err.IS_NULL_PERK)
--         return nil
--     end

--     --- **Check if CreateCharacterMaxSkillObj is nil**
--     if not CreateCharacterMaxSkillObj then
--         errHandler.errMsg("BlockLevel.checkLevelMax(character, perk, CreateCharacterMaxSkillObj)",
--                 " CreateCharacterMaxSkillObj " .. errHandler.err.IS_NULL)
--         return nil
--     end

--     BlockLevel.calculateBlockLevel(character, CreateCharacterMaxSkillObj, perk)
-- end

return BlockLevel