---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)
-- -----------------------------------------------------------------

--- Version 03-11-23 11:56

---@class SkillLimiter

require("lib/CharacterBaseObj")

local blockLevel = require("BlockLevel")
local characterMaxSkill = require("CharacterMaxSkill")
local codePerkDetails = require("CodePerkDetails")
local debugDiagnostics = require("lib/DebugDiagnostics")
local errHandler = require("lib/ErrHandler")
local modDataManager = require("lib/ModDataManager")
local characterPz = require("lib/CharacterPZ")


-- @type CharacterBaseObj
-- local CreateCharacterMaxSkillObj -- = CharacterBaseObj:new()
local SkillLimiter = {}

---@type table
local CharacterMaxSkillTable = {}

---@type string
local characterMaxSkillModData = "characterMaxSkill"

-- **Create Character Max Skill and create ModData**
---@return CharacterBaseObj
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function SkillLimiter.initCharacter(playerIndex, player)
    local localPlayer = getSpecificPlayer(playerIndex) or player
    local player = localPlayer or getPlayer()
    --- **Init Part 1**
    -- CreateCharacterMaxSkillObj = CharacterBaseObj:new()

    
    --- **Check if ModData exists**
    if player:getModData().skillLimiter and not table.isempty(player:getModData().skillLimiter) then
        --print("SkillLimiter - ModData exists")
        --- **Read ModData, get all stats of the character**
        CharacterMaxSkillTable = player:getModData().skillLimiter

        --- **Decode ModData** -- no more decoding
        -- CreateCharacterMaxSkillObj = codePerkDetails.decodePerkDetails(CharacterMaxSkillTable)
    else
        --print("SkillLimiter - ModData not exists")
        --- **Init Part 2**

        --- **Get skill obj**
        local CreateCharacterMaxSkillObj =
            characterMaxSkill.getCreateMaxSkill( debugDiagnostics.characterUpdate() )

        --- **Encode ModData**
        CharacterMaxSkillTable =
            codePerkDetails.encodePerkDetails(CreateCharacterMaxSkillObj)

        --- **Save ModData**
        player:getModData().skillLimiter = CharacterMaxSkillTable

    end
    return CharacterMaxSkillTable
end

--- **Check if character can receive XP without exceeding skill limit**
--- - Utility function for other mods (e.g., UltimateXPTweaker) to check before adding XP
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@return boolean true if can add XP, false if at max level
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function SkillLimiter.canAddXP(character, perk)
    --- **Check if character is null**
    if not character then
        return true  -- Default to true to avoid blocking XP if validation fails
    end

    --- **Check if perk is null**
    if not perk then
        return true
    end

    --- **Check if CharacterMaxSkillTable is initialized**
    if not CharacterMaxSkillTable or table.isempty(CharacterMaxSkillTable) then
        return true  -- If not initialized, don't block XP
    end

    --- **Get current perk level**
    local currentPerkLevel = characterPz.getPerkLevel_PZ(character, perk)
    if not currentPerkLevel then
        return true
    end

    --- **Check base max level (10)**
    local maxLevel = characterPz.EnumNumbers.TEN
    if currentPerkLevel >= maxLevel then
        return false  -- Already at absolute max
    end

    --- **Check custom skill limit from CharacterMaxSkillTable**
    local perkId = perk:getId()
    local details = CharacterMaxSkillTable[perkId]

    if not details then
        return true  -- Perk not tracked, allow XP
    end

    --- **Check if at custom max level**
    if currentPerkLevel >= details.maxLevel then
        return false  -- At or above custom limit
    end

    return true  -- Can add XP
end

--- **Check if character is at max level for a skill**
--- - Inverse semantics of canAddXP for compatibility with existing code
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@return boolean true if at max level, false if can still add XP
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function SkillLimiter.isAtMaxLevel(character, perk)
    return not SkillLimiter.canAddXP(character, perk)
end

--- **Delete modData when character is death**
--- - Triggered when a player is killed.
---@param character IsoGameCharacter
---@return void
local function OnPlayerDeath(character)
    --- **Kill player**
    if character:isDead() then
        --- **Delete ModData**
        character:getModData().skillLimiter = nil
    end
end

--- **Check Level Max**
--- - Triggered when a player gains XP.
---@param character IsoGameCharacter
---@param perk PerkFactory.Perk
---@param level int
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory.Perk
function SkillLimiter.AddXP(character, perk, level)

    --- **Check if character is null**
    if not character then
        errHandler.errMsg("SkillLimiter.AddXP(character, perk, level)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **Check if perk is null**
    if not perk then
        errHandler.errMsg("SkillLimiter.AddXP(character, perk, level)",
                errHandler.err.IS_NULL_PERK)
        return nil
    end

    --- **Check if level is null**
    if not level then
        errHandler.errMsg("SkillLimiter.AddXP(character, perk, level)",
                errHandler.err.IS_NULL_LEVEL)
        return nil
    end

    --- **Check if CharacterMaxSkillTable is null**
    if not CharacterMaxSkillTable then
        errHandler.errMsg("SkillLimiter.AddXP(character, perk, level)",
                " CharacterMaxSkillTable " .. errHandler.err.IS_NULL)
        return nil
    end

    --print("gli XP guadagnati sono: " .. level .. " e sono per: " .. perk:getName())
    -- fix loop
    if level <= 0 then
        --print("SkillLimiter: gli XP sono negativi quindi non continuo")
        return
    end

    -- Calcola currentPerkLevel una volta sola per evitare chiamata Java ridondante
    local currentPerkLevel = characterPz.getPerkLevel_PZ(character, perk)
    blockLevel.calculateBlockLevel(character, perk, level, CharacterMaxSkillTable, currentPerkLevel)
end

--- **Init Character**
--- - Triggered when a player is being created.
local function OnCreatePlayer(playerIndex, player)
    CharacterMaxSkillTable = SkillLimiter.initCharacter(playerIndex, player)
end


Events.OnPlayerDeath.Add(OnPlayerDeath)
Events.AddXP.Add(SkillLimiter.AddXP)
Events.OnCreatePlayer.Add(OnCreatePlayer)





return SkillLimiter